drop table if exists t_security_permissions;
CREATE TABLE t_security_permissions(
  ID INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  IDENTIFIER VARCHAR(64) NOT NULL COMMENT '标识符',
  NAME VARCHAR(64) NOT NULL COMMENT '名称',
  DESCRIPTION TINYTEXT COMMENT '描述',
  DISABLED BOOL NOT NULL COMMENT '有效标识',
  CREATED_BY VARCHAR(8) COMMENT '创建人',
  CREATED_DATE DATETIME COMMENT '创建时间',
  LAST_MODIFIED_BY VARCHAR(8) COMMENT '修改人',
  LAST_MODIFIED_DATE DATETIME COMMENT '修改时间',
  CONSTRAINT UK_PERMISSIONS_IDENTIFIER  UNIQUE(IDENTIFIER)
);

drop table if exists t_security_roles;
CREATE TABLE t_security_roles(
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  IDENTIFIER VARCHAR(64) NOT NULL COMMENT '标识符',
  NAME VARCHAR(64) NOT NULL COMMENT '名称',
  DESCRIPTION TINYTEXT COMMENT '描述',
  DISABLED BOOL NOT NULL COMMENT '有效标识',
  CREATED_BY VARCHAR(8) COMMENT '创建人',
  CREATED_DATE DATETIME COMMENT '创建时间',
  LAST_MODIFIED_BY VARCHAR(8) COMMENT '修改人',
  LAST_MODIFIED_DATE DATETIME COMMENT '修改时间',
  CONSTRAINT PK_T_SYS_ROLES PRIMARY KEY (ID) ,
  CONSTRAINT UK_ROLES_IDENTIFIER  UNIQUE(IDENTIFIER)
);

DROP TABLE if exists t_security_role_permission_map ;
CREATE TABLE t_security_role_permission_map (
  ROLE_ID INT UNSIGNED NOT NULL,
  PERMISSION_ID INT UNSIGNED NOT NULL,
  CONSTRAINT PK_T_ROLE_PERM PRIMARY KEY (ROLE_ID,PERMISSION_ID)
) ;

drop table if exists t_security_users;
CREATE TABLE t_security_users(
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  LOGIN_NAME VARCHAR(10) NOT NULL COMMENT '标识符',
  NAME VARCHAR(8) NOT NULL COMMENT '名称',
  DESCRIPTION TINYTEXT COMMENT '描述',
  MOBILE VARCHAR(11) COMMENT '手机号码',
  EMAIL VARCHAR(64) COMMENT '邮箱',
  ORG_ID INT COMMENT '组织机构ID',
  DISABLED BOOL NOT NULL COMMENT '有效标识',
  PASSWORD VARCHAR(128) ,
  CREATED_BY VARCHAR(8) COMMENT '创建人',
  CREATED_DATE DATETIME COMMENT '创建时间',
  LAST_MODIFIED_BY VARCHAR(8) COMMENT '修改人',
  LAST_MODIFIED_DATE DATETIME COMMENT '修改时间',
  CONSTRAINT PK_T_SYS_USERS PRIMARY KEY (ID) ,
  CONSTRAINT UK_USERS_IDENTIFIER  UNIQUE(LOGIN_NAME)
);

DROP TABLE if exists t_security_user_role_map ;
CREATE TABLE t_security_user_role_map (
  USER_ID INT UNSIGNED NOT NULL,
  ROLE_ID INT UNSIGNED NOT NULL,
  CONSTRAINT PK_USER_ROLE PRIMARY KEY (USER_ID,ROLE_ID)
) ;

DROP TABLE if exists t_security_role_permission_map ;
CREATE TABLE t_security_role_permission_map (
  ROLE_ID INT UNSIGNED NOT NULL,
  PERMISSION_ID INT UNSIGNED NOT NULL,
  CONSTRAINT PK_ROLE_PERM PRIMARY KEY (ROLE_ID,PERMISSION_ID)
) ;


DROP TABLE IF EXISTS t_file_attachments;
CREATE TABLE t_file_attachments (
  ID           VARCHAR(22)     NOT NULL,
  FILE_NAME    TINYTEXT NOT NULL COMMENT '文件名',
  FILE_PATH    TINYTEXT NOT NULL  COMMENT '路径',
  FILE_SUFFIX  VARCHAR(8) COMMENT '文件后缀',
  FILE_SIZE    INT UNSIGNED COMMENT '文件大小',
  CREATED_BY VARCHAR(8) COMMENT '创建人',
  CREATED_DATE DATETIME COMMENT '创建时间',
  LAST_MODIFIED_BY VARCHAR(8) COMMENT '修改人',
  LAST_MODIFIED_DATE DATETIME COMMENT '修改时间',
  PRIMARY KEY (ID)
);


-- 组织机构

DROP TABLE IF EXISTS t_security_orgs;
CREATE TABLE t_security_orgs(
  ID INT UNSIGNED NOT NULL,
  PARENT_ID INT UNSIGNED,
  LEVEL TINYINT UNSIGNED NOT NULL,
  NAME  VARCHAR(32) NOT NULL,
  DESCRIPTION TINYTEXT ,
  ID_ORG_1 INT UNSIGNED,
  ID_ORG_2 INT UNSIGNED,
  ID_ORG_3 INT UNSIGNED,
  ID_ORG_4 INT UNSIGNED,
  ID_ORG_5 INT UNSIGNED,
  ID_ORG_6 INT UNSIGNED,
  ID_ORG_7 INT UNSIGNED,
  ID_ORG_8 INT UNSIGNED,
  ID_ORG_9 INT UNSIGNED,
  CREATED_DATE DATETIME ,
  CREATED_BY VARCHAR(8),
  LAST_MODIFIED_DATE DATETIME ,
  LAST_MODIFIED_BY VARCHAR(8) ,
  CONSTRAINT PK_SECURITY_ORGS PRIMARY KEY (ID)
);
