#app
server:
  port: 8080
  context-path: /api
#
#spring
spring:
  # mysql
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/cyems?autoReconnect=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    testOnBorrow: true
    validationQuery: SELECT 1
    initialSize: 2
    minIdle: 2
    maxActive: 3000
    tomcat:
      initial-size: 3
  http:
    encoding:
      force: true
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
  aop:
    proxy-target-class: true
#
#
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.as.cyems.domain,com.as.security.domain
  typeEnumsPackage: com.as.cyems.domain.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#
#
logging:
  level:
    org: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: TRACE